
name: E2E cross platform

on:
  pull_request:

jobs:
  mac:
    runs-on: macos-latest
    timeout-minutes: 180
    env:
      ELECTRON_CUSTOM_VERSION: 23.0.0
      TEST_MODE: true

    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          cachePrefix: "e2e-crossplatform-mac"
          bootstrap-packages: "@quiet/logger,@quiet/state-manager,@quiet/backend,@quiet/identity,quiet,backend-bundle,e2e-tests"

      # - name: Download DMG
      #   working-directory: ./packages/e2e-tests/Quiet
      #   run: curl -LO https://github.com/TryQuiet/quiet/releases/download/quiet%401.1.0/Quiet-1.1.0.dmg
      - name: Before build
        uses: ./.github/actions/before-build
        with:
          source-path: darwin

      - name: Build App Image
        working-directory: ./packages/desktop
        run: node_modules/.bin/electron-builder -p never --mac 

      - name: Extra steps
        working-directory: ./packages/desktop
        run: VERSION=$(jq -r ".version" package.json) && echo "VERSION=$(jq -r ".version" package.json)" >> $GITHUB_ENV && cd dist && FILE_NAME=$(ls | grep $VERSION) && echo "FILE_NAME=$(ls | grep $VERSION)" >> $GITHUB_ENV && cp $FILE_NAME ../../e2e-tests/Quiet && export FILE_NAME=$FILE_NAME

      # - name: Chmod
      #   working-directory: ./packages/e2e-tests/Quiet
      #   run: chmod +x Quiet-1.1.0.dmg

      - name: Chmod
        working-directory: ./packages/e2e-tests/Quiet
        run: chmod +x $FILE_NAME

      - name: Mount installer file in volume on system
        working-directory: ./packages/e2e-tests/Quiet
        run: hdiutil mount $FILE_NAME 

      - name: Add App file to applications
        run: cd ~ && cp -R "/Volumes/Quiet $VERSION/Quiet.app" /Applications

      - name: Run smoke test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test smoke.crossplatform.test.ts

      - name: Run newUser test - Includes 2 separate application clients
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 35
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test newUser.crossplatform.test.ts



  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    timeout-minutes: 180

    env:
      ELECTRON_CUSTOM_VERSION: 23.0.0
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v2

      - name: Install WM
        run: sudo apt install fluxbox

      - name: Install libfuse2
        run: sudo apt install libfuse2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          cachePrefix: "e2e-crossplatform-linux"
          bootstrap-packages: "@quiet/logger,@quiet/state-manager,@quiet/backend,@quiet/identity,quiet,backend-bundle,e2e-tests"

      - name: Run X11
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox &

      - name: Build App Image
        working-directory: ./packages/desktop
        run: npm run distUbuntu && VERSION=$(jq -r ".version" package.json) && cd dist && FILE_NAME=$(ls | grep $VERSION) && echo "FILE_NAME=$(ls | grep $VERSION)" >> $GITHUB_ENV && cp $FILE_NAME ../../e2e-tests/Quiet && export FILE_NAME=$FILE_NAME

      - name: Chmod
        working-directory: ./packages/e2e-tests/Quiet
        run: chmod +x $FILE_NAME

      - name: Run smoke test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test smoke.crossplatform.test.ts

      - name: Run newUser test - Includes 2 separate application clients
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 35
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test newUser.crossplatform.test.ts

  windows:
    runs-on: windows-2019
    timeout-minutes: 180
    env:
      ELECTRON_CUSTOM_VERSION: 23.0.0
      TEST_MODE: true

    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          cachePrefix: "e2e-crossplatform-windows"
          bootstrap-packages: "@quiet/logger,@quiet/state-manager,@quiet/backend,@quiet/identity,quiet,backend-bundle,e2e-tests"

      # - name: Before build
      #   uses: ./.github/actions/before-build
      #   with:
      #     source-path: win32

      - name: Build App Image
        working-directory: ./packages/desktop
        run: npm run distWin 

      - name: Build App Image
        working-directory: ./packages/desktop
        run: npm run distWin && VERSION=$(jq -r ".version" package.json) && echo "VERSION=$(jq -r ".version" package.json)" >> $GITHUB_ENV && cd dist && FILE_NAME=$(ls | grep $VERSION) && echo "FILE_NAME=$(ls | grep $VERSION)" >> $GITHUB_ENV 
        shell: bash

      - name: Chmod
        working-directory: ./packages/desktop/dist
        run: chmod +x $FILE_NAME
        shell: bash

      - name: Install exe
        run: Start-Process $FILE_NAME -Wait
        working-directory: ./packages/desktop/dist
        shell: powershell

      - name: Kill exe
        run: Stop-Process -Name "Quiet" -Force
        shell: powershell

      - name: Run smoke test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test smoke.crossplatform.test.ts



      # Will be fixed in next tasks 
      # - name: Run newUser test - Includes 2 separate application clients
      #   uses: nick-fields/retry@v2
      #   with:
      #     timeout_minutes: 35
      #     max_attempts: 3
      #     command:  cd packages/e2e-tests && cd packages/e2e-tests && npm run test newUser.crossplatform.test.ts