name: End to end tests

on:
  pull_request:
    paths:
      - packages/nectar
      - packages/waggle
      - packages/integration-tests

# "macos-latest" UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API. https://github.com/DevExpress/testcafe/issues/5352
jobs:
  e2e-linux:
    runs-on: ubuntu-20.04
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install WM
        run: sudo apt install fluxbox

      - name: "Install lerna globally"
        run: npm i -g lerna
      
      - name: Run X11
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox &
      
      - name: Build
        run: lerna bootstrap && lerna run build --scope e2e-tests --stream

      - name: Run tests
        run: lerna run start:e2e --scope e2e-tests --stream
      
      - name: Archive test screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-screenshots-linux
          path: screenshots

  e2e-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      
      - name: "Install lerna globally"
        run: npm i -g lerna

      - name: Build project and run tests
        run: lerna run start:e2eWin --scope e2e-tests --stream
      
      - name: Archive test screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-screenshots-windows
          path: screenshots
