name: End to end tests

on:
  pull_request:
    paths:
      - packages/e2e-tests/**

# "macos-latest" UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API. https://github.com/DevExpress/testcafe/issues/5352
jobs:
  run-e2e-tests:
    uses: ZbayApp/monorepo/.github/workflows/e2e-tests-reusable.yml@ff1fbf8d1853f23ba97c2c00116ef2312ae8977f