name: Regression tests

on:
  pull_request:
    paths:
      - packages/frontend/**

jobs:
  frontend-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Regression tests"
        run: cd packages/frontend && npm run regression-test:ci